name: Cider CI

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    - run: git clone https://github.com/ciderapp/Cider.git cider
    - working-directory: cider
      run: |
        sudo apt-get install -y libarchive-tools snapd
        sudo snap install snapcraft --classic
        echo "$SNAPCRAFT_TOKEN" > /tmp/snapcraft-token
        snapcraft login --with /tmp/snapcraft-token
        yarn
        yarn build
        yarn electron-builder -l snap
        snapcraft push --release=edge Cider.snap
      env:
        SNAPCRAFT_TOKEN: ${{ secrets.SNAPCRAFT_TOKEN }}
